[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vladislav Shlenskii <vladislav.shlenskii@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
setup = "python -OO -m tools setup"
solve = "python -OO -m tools solve"
test = "python -OO -m tools test"

[feature.python.dependencies]
python = "3.12.*"
typer = "*"
typing-extensions = "*"
loguru = "*"
ruff = "*"

[feature.go.dependencies]
go = "1.23.*"

[feature.cxx.dependencies]
fmt = "*"
clangxx = "19.1.*"

[environments]
default = ["python"]
python = ["python"]
go = ["python", "go"]
cxx = ["python", "cxx"]
all = ["python", "go", "cxx"]
